### ISSUE TITLE
Error when opening project locally（app-index.js:33 ClientFetchError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON ）

### ISSUE THREAD

**Issue by Owen0603** [rajput-hemant/lipi#16]
![截屏2024-03-04 23 54 01](https://github.com/rajput-hemant/lipi/assets/12437820/9a4e5e0e-c30b-4339-b1ae-95fe9c32e9f6)

**Comment by Ramdinpuia29** [comment]
I changed the `matcher` value in `middleware.ts` file like this `matcher: ["/((?!.+\\.[\\w]+$|_next).*)", "/", "/(api|trpc)(.*)"],`  and it works.

Not really sure what's the main cause but I guess it's the regex that blocks `/api/auth/session` route that `getServerSession` function cannot be called.

https://nextjs.org/docs/app/building-your-application/routing/middleware#matcher

**Comment by rajput-hemant** [comment]
Hey @Ramdinpuia29 , sorry for the late reply. My exams were going on, so I didn't get time to check out my repos. Thanks for pointing out the issue with the matcher from the clerks middleware configuration. I'll change the matcher in the next commit.
