### ISSUE TITLE
Typo in pricing...

### ISSUE THREAD

**Issue by shaaanuu** [rajput-hemant/lipi#40]
In the pricing section, under pro plan it says '1 year day page history' instead of "1 year page history".

**Comment by rajput-hemant** [comment]
hey @shaaanuu,

thank you for pointing that out
could you please make a PR for the correction? additionally, while you're at it, could you also fix another typo in the Pro plan card? It should read:

```
₹499/mo
Billed annually. ₹555 billed monthly
```

**Comment by shaaanuu** [comment]
Assign me

**Comment by shaaanuu** [comment]
Done... And i am little confused about
₹499/mo
₹555 billed monthly

It should be ₹5,988 billed annually, right? Maybe i am wrong...
(Missed alot of maths class... ; ) )

**Comment by shaaanuu** [comment]
#41

**Comment by rajput-hemant** [comment]
> Done... And i am little confused about ₹499/mo ₹555 billed monthly
> 
> It should be ₹5,988 billed annually, right? Maybe i am wrong... (Missed alot of maths class... ; ) )

it's like if you buy an annual subscription, itll cost ₹499/mo, but if you buy a monthly subscription, itll cost ₹555/mo
i hope if clears yours confusion

and thanks for the pr 👍🏻
